name: CI and CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: yarn install --frozen-lockfile
    - name: setup firebase emulator
      run: npx firebase setup:emulators:firestore 
    - name: yarn lint
      run: yarn lint
    - name: yarn test:unit
      run: yarn test:unit
    - name: yarn test:e2e
      run: yarn test:e2e
    - name: deploy to Firebase Hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy
    - name: Install firebase-tools
      run: yarn global add firebase-tools
    - name: Create .env file
      run: echo "${{ secrets.ENV_ }}" > .env
    - name: Install dependencies
      run: yarn --network-timeout 100000
    - name: Build app
      run: yarn build
    - name: Deploy
      run: firebase deploy --project $FIREBASE_PROJECT_ID --token $FIREBASE
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
